// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// FFBS
arma::mat FFBS(arma::mat Y, arma::mat F_, arma::mat V, arma::mat G, arma::mat W, arma::colvec m_0, arma::mat C_0);
RcppExport SEXP _ideq_FFBS(SEXP YSEXP, SEXP F_SEXP, SEXP VSEXP, SEXP GSEXP, SEXP WSEXP, SEXP m_0SEXP, SEXP C_0SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type Y(YSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type F_(F_SEXP);
    Rcpp::traits::input_parameter< arma::mat >::type V(VSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type G(GSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type W(WSEXP);
    Rcpp::traits::input_parameter< arma::colvec >::type m_0(m_0SEXP);
    Rcpp::traits::input_parameter< arma::mat >::type C_0(C_0SEXP);
    rcpp_result_gen = Rcpp::wrap(FFBS(Y, F_, V, G, W, m_0, C_0));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_ideq_FFBS", (DL_FUNC) &_ideq_FFBS, 7},
    {NULL, NULL, 0}
};

RcppExport void R_init_ideq(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
