// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// mvnorm
arma::colvec mvnorm(arma::colvec mean, arma::mat Sigma);
RcppExport SEXP _ideq_mvnorm(SEXP meanSEXP, SEXP SigmaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::colvec >::type mean(meanSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type Sigma(SigmaSEXP);
    rcpp_result_gen = Rcpp::wrap(mvnorm(mean, Sigma));
    return rcpp_result_gen;
END_RCPP
}
// dstm
List dstm(arma::mat Y, CharacterVector model, const int n_samples, const int p, const bool verbose, const bool sample_sigma2);
RcppExport SEXP _ideq_dstm(SEXP YSEXP, SEXP modelSEXP, SEXP n_samplesSEXP, SEXP pSEXP, SEXP verboseSEXP, SEXP sample_sigma2SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type Y(YSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type model(modelSEXP);
    Rcpp::traits::input_parameter< const int >::type n_samples(n_samplesSEXP);
    Rcpp::traits::input_parameter< const int >::type p(pSEXP);
    Rcpp::traits::input_parameter< const bool >::type verbose(verboseSEXP);
    Rcpp::traits::input_parameter< const bool >::type sample_sigma2(sample_sigma2SEXP);
    rcpp_result_gen = Rcpp::wrap(dstm(Y, model, n_samples, p, verbose, sample_sigma2));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_ideq_mvnorm", (DL_FUNC) &_ideq_mvnorm, 2},
    {"_ideq_dstm", (DL_FUNC) &_ideq_dstm, 6},
    {NULL, NULL, 0}
};

RcppExport void R_init_ideq(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
