# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Samples from a multivariate normal distribution
#'
#' @export
#' @examples
#' # Duhh...nothing yet
#' @importFrom Rcpp sourceCpp evalCpp
#' @useDynLib ideq
mvnorm <- function(mean, Sigma) {
    .Call('_ideq_mvnorm', PACKAGE = 'ideq', mean, Sigma)
}

#' Fits a DSTM using a wishart prior for W
#'
#' @export
#' @examples
#' # Duhh...nothing yet
#' @importFrom Rcpp sourceCpp evalCpp
#' @useDynLib ideq
eof <- function(Y, F, G_0, Sigma_G_inv, m_0, C_0, C_W, params, proc_model, n_samples, verbose) {
    .Call('_ideq_eof', PACKAGE = 'ideq', Y, F, G_0, Sigma_G_inv, m_0, C_0, C_W, params, proc_model, n_samples, verbose)
}

#' Fits an integrodifference equation model (IDE)
#'
#' @export
#' @examples @importFrom Rcpp sour
#' # Duhh...nothing yet
#'ceCpp evalCpp
#' @useDynLib ideq
ide_sc <- function(Y, locs, m_0, C_0, mu_kernel_mean, mu_kernel_var, Sigma_kernel_scale, C_W, params, n_samples, verbose) {
    .Call('_ideq_ide_sc', PACKAGE = 'ideq', Y, locs, m_0, C_0, mu_kernel_mean, mu_kernel_var, Sigma_kernel_scale, C_W, params, n_samples, verbose)
}

#' Fits a integrodifference equation model (IDE)
#'
#' @export
#' @examples @importFrom Rcpp sour
#' # Duhh...nothing yet
#'ceCpp evalCpp
#' @useDynLib ideq
ide_sv <- function(Y, locs, m_0, C_0, mu_kernel_mean, mu_kernel_var, Sigma_kernel_scale, C_W, params, n_samples, verbose) {
    .Call('_ideq_ide_sv', PACKAGE = 'ideq', Y, locs, m_0, C_0, mu_kernel_mean, mu_kernel_var, Sigma_kernel_scale, C_W, params, n_samples, verbose)
}

