# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

mvnorm <- function(mean, Sigma) {
    .Call('_ideq_mvnorm', PACKAGE = 'ideq', mean, Sigma)
}

#' Performs FFBS
#'
#' @param Y S by T matrix containing response variable
#' @param F_ S by p matrix defining \eqn{Y_t = F \theta_t + V}
#' @param V S by S variance-covariance matrix of \eqn{V}
#' @param G p by p matrix defining \eqn{\theta_t = G \theta_{t-1} + W}
#' @param W p by p variance-covariance matrix of \eqn{W}
#' @param m_0 p by 1 column vector for a priori mean of \eqn{\theta}
#' @param C_0 p by p matrix of for a priori variance-covariance matrix of \eqn{\theta}
#'
#' @keyword IDE, Kalman, Filter
#' @export
#' @examples
#' # Duhh...nothing yet
#' @useDynLib ideq
#' @importFrom Rcpp sourceCpp
Ideq <- function(Y, F_, V, G, W, m_0, C_0, n_samples, verbose = FALSE) {
    .Call('_ideq_Ideq', PACKAGE = 'ideq', Y, F_, V, G, W, m_0, C_0, n_samples, verbose)
}

