# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

ldiwishart <- function(x, df, scale) {
    .Call('_ideq_ldiwishart', PACKAGE = 'ideq', x, df, scale)
}

#' Samples from a multivariate normal distribution
#'
#' @export
#' @examples
#' # Duhh...nothing yet
#' @importFrom Rcpp sourceCpp evalCpp
#' @useDynLib ideq
rmvnorm <- function(mean, Sigma) {
    .Call('_ideq_rmvnorm', PACKAGE = 'ideq', mean, Sigma)
}

eof <- function(Y, F, G_0, Sigma_G_inv, m_0, C_0, C_W, params, proc_model, n_samples, verbose) {
    .Call('_ideq_eof', PACKAGE = 'ideq', Y, F, G_0, Sigma_G_inv, m_0, C_0, C_W, params, proc_model, n_samples, verbose)
}

ide <- function(Y, locs, m_0, C_0, mu_kernel_mean, mu_kernel_var, K, Sigma_kernel_scale, C_W, params, n_samples, verbose) {
    .Call('_ideq_ide', PACKAGE = 'ideq', Y, locs, m_0, C_0, mu_kernel_mean, mu_kernel_var, K, Sigma_kernel_scale, C_W, params, n_samples, verbose)
}

